apiVersion: v1

kind: Service

metadata:

  name: tomcat-service

  namespace: taly-tst-payflow

spec:

  type: LoadBalancer

  selector:

    app: tomcat

  ports:

    - port: 80

      protocol: TCP

      targetPort: 8080
	  
    - port: 443

      protocol: TCP

      targetPort: 8443
	

---

apiVersion: apps/v1                          

kind: Deployment

metadata:

  name: tomcat-deployment

  namespace: taly-tst-payflow

spec:

  replicas: 3

  selector:

    matchLabels:

      app: tomcat

  template:

    metadata:

      labels:

        app: tomcat

    spec:

      volumes:
	  
      - name: secret-volume
	  
        secret:
		
           secretName: tomcat-certs-keys
		   
      - name: configmap-volume
	  
        configMap:
		
          name: tomcatconfigmap 

      containers:

        - name: tomcat-container

          image: gcr.io/kodekloud/centos-ssh-enabled:tomcat

          ports:

            - containerPort: 8080
			- containerPort: 8443
			
		    volumeMounts:
			
				- name: tomcat-war
				
				  mountPath: /usr/local/tomcat/webapps/
      volumes:
	  
		- name: tomcat-war
		
		  persistentVolumeClaim:
		  
			claimName: pvc-nfs-tomcat
