apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: taly-tst-payflow
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: DAPPMSTR02.local:31320/tomcat:9.9
        ports:
        - containerPort: 8443
        - containerPort: 8080